name: Terraform
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: 'Log into Azure using github secret AZURE_CREDENTIALS'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: TerraformFormat
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 'latest'
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./terraform"
    - name: Terraform
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 'latest'
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_version: 'latest'
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./terraform"
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 'latest'
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"
    - name: Terraforaa
      if: github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 'latest'
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"
