name: Azure ARM

on: [push]
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          inlineScript: az vm create -n MyVm -g test --image UbuntuLTS
